/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSobreRouteImport } from './routes/_layout/sobre'
import { Route as LayoutResetPasswordRouteImport } from './routes/_layout/reset-password'
import { Route as LayoutRecuperarSenhaRouteImport } from './routes/_layout/recuperar-senha'
import { Route as LayoutMinhaContaRouteImport } from './routes/_layout/minha-conta'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutCheckoutRouteImport } from './routes/_layout/checkout'
import { Route as LayoutCatalogoRouteImport } from './routes/_layout/catalogo'
import { Route as LayoutCarrinhoRouteImport } from './routes/_layout/carrinho'
import { Route as LayoutCadastroRouteImport } from './routes/_layout/cadastro'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAcessoNegadoRouteImport } from './routes/_layout/acesso-negado'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as ApiPublicMpWebhookRouteImport } from './routes/api/public/mp-webhook'
import { Route as LayoutProdutoSlugRouteImport } from './routes/_layout/produto.$slug'
import { Route as LayoutAdminSubcategoriasRouteImport } from './routes/_layout/admin/subcategorias'
import { Route as LayoutAdminProdutosRouteImport } from './routes/_layout/admin/produtos'
import { Route as LayoutAdminPedidosRouteImport } from './routes/_layout/admin/pedidos'
import { Route as LayoutAdminEnergiasRouteImport } from './routes/_layout/admin/energias'
import { Route as LayoutAdminCuponsRouteImport } from './routes/_layout/admin/cupons'
import { Route as LayoutAdminCategoriasRouteImport } from './routes/_layout/admin/categorias'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSobreRoute = LayoutSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResetPasswordRoute = LayoutResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecuperarSenhaRoute = LayoutRecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMinhaContaRoute = LayoutMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCheckoutRoute = LayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCatalogoRoute = LayoutCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCarrinhoRoute = LayoutCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCadastroRoute = LayoutCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAcessoNegadoRoute = LayoutAcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const ApiPublicMpWebhookRoute = ApiPublicMpWebhookRouteImport.update({
  id: '/api/public/mp-webhook',
  path: '/api/public/mp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProdutoSlugRoute = LayoutProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminSubcategoriasRoute =
  LayoutAdminSubcategoriasRouteImport.update({
    id: '/subcategorias',
    path: '/subcategorias',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminProdutosRoute = LayoutAdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPedidosRoute = LayoutAdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminEnergiasRoute = LayoutAdminEnergiasRouteImport.update({
  id: '/energias',
  path: '/energias',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminCuponsRoute = LayoutAdminCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminCategoriasRoute = LayoutAdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => LayoutAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/acesso-negado': typeof LayoutAcessoNegadoRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/cadastro': typeof LayoutCadastroRoute
  '/carrinho': typeof LayoutCarrinhoRoute
  '/catalogo': typeof LayoutCatalogoRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/login': typeof LayoutLoginRoute
  '/minha-conta': typeof LayoutMinhaContaRoute
  '/recuperar-senha': typeof LayoutRecuperarSenhaRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/sobre': typeof LayoutSobreRoute
  '/admin/categorias': typeof LayoutAdminCategoriasRoute
  '/admin/cupons': typeof LayoutAdminCuponsRoute
  '/admin/energias': typeof LayoutAdminEnergiasRoute
  '/admin/pedidos': typeof LayoutAdminPedidosRoute
  '/admin/produtos': typeof LayoutAdminProdutosRoute
  '/admin/subcategorias': typeof LayoutAdminSubcategoriasRoute
  '/produto/$slug': typeof LayoutProdutoSlugRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRoutesByTo {
  '/acesso-negado': typeof LayoutAcessoNegadoRoute
  '/cadastro': typeof LayoutCadastroRoute
  '/carrinho': typeof LayoutCarrinhoRoute
  '/catalogo': typeof LayoutCatalogoRoute
  '/checkout': typeof LayoutCheckoutRoute
  '/login': typeof LayoutLoginRoute
  '/minha-conta': typeof LayoutMinhaContaRoute
  '/recuperar-senha': typeof LayoutRecuperarSenhaRoute
  '/reset-password': typeof LayoutResetPasswordRoute
  '/sobre': typeof LayoutSobreRoute
  '/': typeof LayoutIndexRoute
  '/admin/categorias': typeof LayoutAdminCategoriasRoute
  '/admin/cupons': typeof LayoutAdminCuponsRoute
  '/admin/energias': typeof LayoutAdminEnergiasRoute
  '/admin/pedidos': typeof LayoutAdminPedidosRoute
  '/admin/produtos': typeof LayoutAdminProdutosRoute
  '/admin/subcategorias': typeof LayoutAdminSubcategoriasRoute
  '/produto/$slug': typeof LayoutProdutoSlugRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/admin': typeof LayoutAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/acesso-negado': typeof LayoutAcessoNegadoRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/cadastro': typeof LayoutCadastroRoute
  '/_layout/carrinho': typeof LayoutCarrinhoRoute
  '/_layout/catalogo': typeof LayoutCatalogoRoute
  '/_layout/checkout': typeof LayoutCheckoutRoute
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/minha-conta': typeof LayoutMinhaContaRoute
  '/_layout/recuperar-senha': typeof LayoutRecuperarSenhaRoute
  '/_layout/reset-password': typeof LayoutResetPasswordRoute
  '/_layout/sobre': typeof LayoutSobreRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/categorias': typeof LayoutAdminCategoriasRoute
  '/_layout/admin/cupons': typeof LayoutAdminCuponsRoute
  '/_layout/admin/energias': typeof LayoutAdminEnergiasRoute
  '/_layout/admin/pedidos': typeof LayoutAdminPedidosRoute
  '/_layout/admin/produtos': typeof LayoutAdminProdutosRoute
  '/_layout/admin/subcategorias': typeof LayoutAdminSubcategoriasRoute
  '/_layout/produto/$slug': typeof LayoutProdutoSlugRoute
  '/api/public/mp-webhook': typeof ApiPublicMpWebhookRoute
  '/_layout/admin/': typeof LayoutAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/admin'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/login'
    | '/minha-conta'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/energias'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/subcategorias'
    | '/produto/$slug'
    | '/api/public/mp-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/acesso-negado'
    | '/cadastro'
    | '/carrinho'
    | '/catalogo'
    | '/checkout'
    | '/login'
    | '/minha-conta'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sobre'
    | '/'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/energias'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/subcategorias'
    | '/produto/$slug'
    | '/api/public/mp-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/acesso-negado'
    | '/_layout/admin'
    | '/_layout/cadastro'
    | '/_layout/carrinho'
    | '/_layout/catalogo'
    | '/_layout/checkout'
    | '/_layout/login'
    | '/_layout/minha-conta'
    | '/_layout/recuperar-senha'
    | '/_layout/reset-password'
    | '/_layout/sobre'
    | '/_layout/'
    | '/_layout/admin/categorias'
    | '/_layout/admin/cupons'
    | '/_layout/admin/energias'
    | '/_layout/admin/pedidos'
    | '/_layout/admin/produtos'
    | '/_layout/admin/subcategorias'
    | '/_layout/produto/$slug'
    | '/api/public/mp-webhook'
    | '/_layout/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiPublicMpWebhookRoute: typeof ApiPublicMpWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sobre': {
      id: '/_layout/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof LayoutSobreRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reset-password': {
      id: '/_layout/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof LayoutResetPasswordRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recuperar-senha': {
      id: '/_layout/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof LayoutRecuperarSenhaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/minha-conta': {
      id: '/_layout/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof LayoutMinhaContaRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/checkout': {
      id: '/_layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof LayoutCheckoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/catalogo': {
      id: '/_layout/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof LayoutCatalogoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/carrinho': {
      id: '/_layout/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof LayoutCarrinhoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/cadastro': {
      id: '/_layout/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof LayoutCadastroRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/acesso-negado': {
      id: '/_layout/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof LayoutAcessoNegadoRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/api/public/mp-webhook': {
      id: '/api/public/mp-webhook'
      path: '/api/public/mp-webhook'
      fullPath: '/api/public/mp-webhook'
      preLoaderRoute: typeof ApiPublicMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/produto/$slug': {
      id: '/_layout/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof LayoutProdutoSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/subcategorias': {
      id: '/_layout/admin/subcategorias'
      path: '/subcategorias'
      fullPath: '/admin/subcategorias'
      preLoaderRoute: typeof LayoutAdminSubcategoriasRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/produtos': {
      id: '/_layout/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof LayoutAdminProdutosRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/pedidos': {
      id: '/_layout/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof LayoutAdminPedidosRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/energias': {
      id: '/_layout/admin/energias'
      path: '/energias'
      fullPath: '/admin/energias'
      preLoaderRoute: typeof LayoutAdminEnergiasRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/cupons': {
      id: '/_layout/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof LayoutAdminCuponsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/categorias': {
      id: '/_layout/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof LayoutAdminCategoriasRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminCategoriasRoute: typeof LayoutAdminCategoriasRoute
  LayoutAdminCuponsRoute: typeof LayoutAdminCuponsRoute
  LayoutAdminEnergiasRoute: typeof LayoutAdminEnergiasRoute
  LayoutAdminPedidosRoute: typeof LayoutAdminPedidosRoute
  LayoutAdminProdutosRoute: typeof LayoutAdminProdutosRoute
  LayoutAdminSubcategoriasRoute: typeof LayoutAdminSubcategoriasRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminCategoriasRoute: LayoutAdminCategoriasRoute,
  LayoutAdminCuponsRoute: LayoutAdminCuponsRoute,
  LayoutAdminEnergiasRoute: LayoutAdminEnergiasRoute,
  LayoutAdminPedidosRoute: LayoutAdminPedidosRoute,
  LayoutAdminProdutosRoute: LayoutAdminProdutosRoute,
  LayoutAdminSubcategoriasRoute: LayoutAdminSubcategoriasRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAcessoNegadoRoute: typeof LayoutAcessoNegadoRoute
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutCadastroRoute: typeof LayoutCadastroRoute
  LayoutCarrinhoRoute: typeof LayoutCarrinhoRoute
  LayoutCatalogoRoute: typeof LayoutCatalogoRoute
  LayoutCheckoutRoute: typeof LayoutCheckoutRoute
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutMinhaContaRoute: typeof LayoutMinhaContaRoute
  LayoutRecuperarSenhaRoute: typeof LayoutRecuperarSenhaRoute
  LayoutResetPasswordRoute: typeof LayoutResetPasswordRoute
  LayoutSobreRoute: typeof LayoutSobreRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProdutoSlugRoute: typeof LayoutProdutoSlugRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAcessoNegadoRoute: LayoutAcessoNegadoRoute,
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutCadastroRoute: LayoutCadastroRoute,
  LayoutCarrinhoRoute: LayoutCarrinhoRoute,
  LayoutCatalogoRoute: LayoutCatalogoRoute,
  LayoutCheckoutRoute: LayoutCheckoutRoute,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutMinhaContaRoute: LayoutMinhaContaRoute,
  LayoutRecuperarSenhaRoute: LayoutRecuperarSenhaRoute,
  LayoutResetPasswordRoute: LayoutResetPasswordRoute,
  LayoutSobreRoute: LayoutSobreRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProdutoSlugRoute: LayoutProdutoSlugRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ApiPublicMpWebhookRoute: ApiPublicMpWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
